### ISSUE TITLE
commonapi-someip application not able to get message from service.

### ISSUE THREAD

**Issue by rlokanathan** [COVESA/capicxx-someip-runtime#11]
Hi,

Currrently, I am using the helloworld application from the commonapi-someip wiki page. With that application I tested in both Linux and Windows locally it was working. Now, my next stage is to run the client in Windows and the service in the Linux. Currently, the service application is using the below configuration.

helloworld-service.json (in Linux):

    {
    "unicast":"192.168.56.107",
    "logging":
    {
        "level":"debug",
        "console":"true",
                "file":{"enable":"true", "path":"/tmp/vsomeip.log"},
                "dlt":"false"
    },

    "applications":
    [
        {
            "name":"HelloWorldService",
            "id":"0x1277"
        }
    ],

    "services":
    [
        {
            "service":"0x1234",
            "instance":"0x5678",
            "reliable" : { "port" : "30509", "enable-magic-cookies" : "false" }
        }
    ],

    "routing":"HelloWorldService",
    "service-discovery":
    {
        "enable":"true",
        "multicast":"224.0.0.1",
        "port":"30490",
        "protocol":"udp"
    }
    }

This is my helloworld-client.json (in Windows):

    {
    "unicast":"192.168.56.1",
	"netmask":"255.255.255.0",
    "logging":
    {
        "level":"debug",
        "console":"true",
		"file":{"enable":"true", "path":"vsomeip.log"},
		"dlt":"false"
    },

    "applications":
    [
        {
            "name":"HelloWorldClient",
            "id":"0x1343"
        }
    ],
	"clients" :
    [
        {
            "service" : "0x1234",
            "instance" : "0x5678",
            "reliable" : "30509"
        }
    ],
    "routing":"HelloWorldClient",
    "service-discovery":
    {
        "enable":"true",
		"multicast":"224.0.0.1",
		"port":"30490",
		"protocol":"udp"
    }
    }

At the moment, the client is able to detect the service but its not able to get the message from the service. In this case it should print out "Got message: 'Bob'". But for me it showing "Got message: ' ' ". And over at the client side it shows as:

    2020-08-19 12:15:45.517289 [info] vSomeIP 2.14.16 | (default)
    Available...
    2020-08-19 12:15:48.836873 [error] Routing info for remote service could not be found! (1343): [1234.5678.007b] 0001
    Got message:
    Got Status: 4
    2020-08-19 12:15:53.837955 [info] RELEASE(1343): [1234.5678]

Can someone guide me through this process. Is the configuration is wrong ? How can I run client in windows and service in Linux separately. Both are using the same address range.

**Comment by lutzbichler** [comment]
Did you set the multicast route?
