### ISSUE TITLE
Cannot compile commonapi-someip-runtime v3.2.0

### ISSUE THREAD

**Issue by rlokanathan** [COVESA/capicxx-someip-runtime#14]
Hi, I am not able to compile the commonapi-someip-runtime library.
This is my current setup:

VM: Apertis Pro
vsomeip: 3.1.7.1
commonapi-runtime: 3.2.0

When I tried to execute the make command after cmake, it shows error in the Types.hpp

capicxx-someip-runtime-3.2.0/include/CommonAPI/SomeIP/Types.hpp:37:18: error: ‘event_type_e’ in namespace ‘vsomeip’ does not name a type
 typedef vsomeip::event_type_e event_type_e;
                  ^~~~~~~~~~~~
capicxx-someip-runtime-3.2.0/include/CommonAPI/SomeIP/Types.hpp:37:9: note: suggested alternative: ‘offer_type_e’
 typedef vsomeip::event_type_e event_type_e;
         ^~~~~~~
         offer_type_e
capicxx-someip-runtime-3.2.0/include/CommonAPI/SomeIP/Types.hpp:38:18: error: ‘reliability_type_e’ in namespace ‘vsomeip’ does not name a type
 typedef vsomeip::reliability_type_e reliability_type_e;
                  ^~~~~~~~~~~~~~~~~~
capicxx-someip-runtime-3.2.0/include/CommonAPI/SomeIP/Types.hpp:38:9: note: suggested alternative: ‘message_type_e’
 typedef vsomeip::reliability_type_e reliability_type_e;
         ^~~~~~~
         message_type_e
capicxx-someip-runtime-3.2.0/include/CommonAPI/SomeIP/Types.hpp:45:18: error: ‘uid_t’ in namespace ‘vsomeip’ does not name a type
 typedef vsomeip::uid_t uid_t;
                  ^~~~~
capicxx-someip-runtime-3.2.0/include/CommonAPI/SomeIP/Types.hpp:46:18: error: ‘gid_t’ in namespace ‘vsomeip’ does not name a type
 typedef vsomeip::gid_t gid_t;
                  ^~~~~

I am not sure what error is this, but when I run cmake command, it selects vsomeip3.1.7.1.

**Comment by lutzbichler** [comment]
Looks as if old (v2) vsomeip header files are found first.

**Comment by ManikanthaP** [comment]
what are the compatible versions of commonapi-core-runtime and vsomeip and commonapi-someip runtime ??

**Comment by goncaloalmeida** [comment]
hello all,
please use the last version of all projects.
The vsomeip reported version is no longer supported.
