### ISSUE TITLE
communication between 2 machines using someip not working

### ISSUE THREAD

**Issue by supriyar-1** [COVESA/capicxx-someip-runtime#16]
I followed the instructions given in SOMEIP in 10 (https://genivi-oss.atlassian.net/wiki/spaces/COMMONAPICPP/pages/5472320/CommonAPI+C+SOME+IP+in+10+minutes) and it is working fine on one machine.
But it is not working when I am trying to do it on two ubuntu machines.
I used the same json files as in the tutorial with unicast changed according to my machines.
Routing information has been added：
sudo route add -host 224.244.224.245 dev eth1

**Comment by lutzbichler** [comment]
Not working means it does not find the service? Please show some logs and your routing table.

**Comment by lutzbichler** [comment]
Not enough information available.
