### ISSUE TITLE
Issues with TC8 ETS tests defined in Open Alliance documents

### ISSUE THREAD

**Issue by maingig** [COVESA/capicxx-someip-runtime#17]
Version 3.1.12.17
I am referring to Version 3.0 of the Open Alliance document

I have defined a service with franca/CommonAPI which matches the API defined in this document for the Enhanced Testability Service.

Most of the APIs are defined such that the service returns the input data
1. Fixed UTF16 strings are not returned at all - the payload is empty. (SOMEIP_ETS_046_echoUTF16FIXED)
2. Fixed UTF8 and UTF16 strings.  If I send a string shorter than specified, the message response is Ok rather than Malformed.  This works fine if the strings are longer than indicated. (SOMEIP_ETS_064_String_UTF16FIXED_too_short, SOMEIP_ETS_066_String_UTF8FIXED_too_short)
3. Fixed Array - sending a string longer than allowed crashes the service in InputStream. The response should be a malformed message. (SOMEIP_ETS_001_Array_Length_longer_as_message_length_allows_it)
4. Sending a Fixed Array that is too short produces an error rather than stripping the payload. (SOMEIP_ETS_003_Array_Length_too_short_strips_Payload)

**Comment by goncaloalmeida** [comment]
Hello,
sorry for the late answer. Please retest with the latest version of all projects.
The reported version is no longer supported.
