### ISSUE TITLE
How to  prevent Get of Attribute From Client Base On commonAPI+Vsomeip

### ISSUE THREAD

**Issue by liu8232303** [COVESA/capicxx-someip-runtime#20]
I have a attribute in service，i want to decide whether the client can use get of Attribute according to the conditions,
If the conditions are not met, then ignore get of Attribute from client;  if the conditions are met, 
the return get value of attribute to client 。
But，see  generate code:
    **COMMONAPI_EXPORT virtual const int32_t &getXAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getXAttribute();
    }**
it must return value No matter condition。
What should I do?

**Comment by goncaloalmeida** [comment]
@liu8232303 this is a normal get, not a conditional get.
This type of operation should be done on the application side, not the generated code side.
