### ISSUE TITLE
capicxx-someip-runtime 3.2.0 is not compatible with vsomeip 3.3.0 and 3.3.8

### ISSUE THREAD

**Issue by shivamkumar123** [COVESA/capicxx-someip-runtime#25]
In Android Automotive OS 13, we attempted to use Capicxx-someip-runtime 3.2.0 with vsomeip 3.3.0 but encountered compilation problems.
It displays a use of deprecated VSOMEIP_DEPRECATED_UID_GID api error.
Could you please available the working version of capicxx-someip-runtime with latest version of vsomeip.

**Comment by goncaloalmeida** [comment]
hello @shivamkumar123 
please use the last release of all projects, in principle this problem will not occur.
