### ISSUE TITLE
[3.2.3-r8] Build throw errors

### ISSUE THREAD

**Issue by lijie-jiang** [COVESA/capicxx-someip-runtime#34]
I try to build the 3.2.3-r8 and get errors below:
/home/lijiejiang/github/capicxx-someip-runtime/src/CommonAPI/SomeIP/ClientId.cpp: In constructor 'CommonAPI::SomeIP::ClientId::ClientId(CommonAPI::SomeIP::client_id_t, const vsomeip_sec_client_t*, const string&)':
/home/lijiejiang/github/capicxx-someip-runtime/src/CommonAPI/SomeIP/ClientId.cpp:37:40: error: 'const struct vsomeip_sec_client_t' has no member named 'user'
   37 |       uid_ {_sec_client ? _sec_client->user : 0xffffffff},
      |                                        ^~~~
/home/lijiejiang/github/capicxx-someip-runtime/src/CommonAPI/SomeIP/ClientId.cpp:38:40: error: 'const struct vsomeip_sec_client_t' has no member named 'group'
   38 |       gid_ {_sec_client ? _sec_client->group : 0xffffffff},
      |                                        ^~~~~
/home/lijiejiang/github/capicxx-someip-runtime/src/CommonAPI/SomeIP/ClientId.cpp:39:16: error: cannot convert '<brace-enclosed initializer list>' to 'CommonAPI::SomeIP::uid_t' {aka 'unsigned int'} in initialization
   39 |       env_(_env) {
      |                ^
/home/lijiejiang/github/capicxx-someip-runtime/src/CommonAPI/SomeIP/ClientId.cpp:39:16: error: cannot convert '<brace-enclosed initializer list>' to 'CommonAPI::SomeIP::gid_t' {aka 'unsigned int'} in initialization
/home/lijiejiang/github/capicxx-someip-runtime/src/CommonAPI/SomeIP/ClientId.cpp:42:53: error: 'const struct vsomeip_sec_client_t' has no member named 'host'
   42 |         hostAddress_ = addressToString(_sec_client->host);
      |                                                     ^~~~

**Comment by goncaloalmeida** [comment]
@lijie-jiang you should use the last release of vsomeip-lib.
